### ISSUE TITLE
'events' and 'chromeEvents' seem to be missing from Maven release 2.3.0

### ISSUE THREAD

**Issue by mylesbennett** [satoshun/RxWebView#37]
This is a very promising library, however, I can't get it to work according to your Readme instructions.

Change line 30 in your app/build.gradle
from:
implementation project(':rxwebview')
to:
implementation "com.github.satoshun.RxWebView:rxwebview:2.3.0"

... and then re-sync. I get unresolved references on 'events' and 'chromeEvents' in the MainActivity

**Comment by satoshun** [comment]
thx, I will watch it on the weekend.

**Comment by satoshun** [comment]
i released v2.3.1. it can call `RxWebChromeClient.events` and `RxWebViewClient.events` methods from Java. maybe it's a compatible old versions.

**Comment by mylesbennett** [comment]
thnx - works fine now
